Bootstrap: docker
From: kwellswrasman/rnaseq_general:v2

%environment
    # This will be sourced in all runs
    . /shell-hook.sh

%runscript
    # This is the command run when you call the container
    exec "$@"