Bootstrap: docker
From: kwellswrasman/dorado:v3

%environment
    # This will be sourced in all runs
    . /shell-hook.sh

%runscript
    # This is the command run when you call the container
    exec "$@"