# Get base image
# Start with mixcr. See versions here 
# https://github.com/milaboratory/mixcr/pkgs/container/mixcr%2Fmixcr
FROM ghcr.io/milaboratory/mixcr/mixcr:4.6.0

# Copy license
COPY mi.license /opt/mixcr/mi.license