name: human

channels:
  - conda-forge
  - bioconda
  - defaults
  - agbiome
dependencies:
  - pip >=1.4
  - pysam >= 0.22.1
  - star >= 2.7.11a
  - cutadapt >= 4.5
  - bbtools >= 37.62
  - fastqc >= 0.11.8
  - samtools >= 1.16.1
  - subread >= 2.0.3
  - bedtools >= 2.30.0
  - deeptools >= 3.5.1
  - rmats >=4.3.0